### ISSUE TITLE
Unable to connect to RabbitMQ with self signed certificate from broker ingress

### ISSUE THREAD

**Issue by erictg** [knative-sandbox/eventing-rabbitmq#1044]
**Describe the bug**
I'm unable to submit messages to knative broker ingress with a RabbitMQ backend. The error inside of the broker ingress is:
`{"level":"error","ts":"2023-01-23T19:38:29.715Z","logger":"rabbitmq-ingress","caller":"rabbit/setup.go:121","msg":"failed to connect to RabbitMQ","commit":"0a00e86-dirty","error":"x509: certificate signed by unknown authority","stacktrace":"knative.dev/eventing-rabbitmq/pkg/rabbit.(*RabbitMQHelper).SetupRabbitMQ\n\tknative.dev/eventing-rabbitmq/pkg/rabbit/setup.go:121\nmain.main.func1\n\tknative.dev/eventing-rabbitmq/cmd/ingress/main.go:99"}`

To me this means that the ingress controller would need to be provided with the certificate authority for RabbitMQ. Looking through the docs and code, I can't figure out a way to provide this.

When listing brokers, it appears as online with no issues:
```
~ kn broker ls -n mod-patient                                            
NAME      URL                                                           AGE   CONDITIONS   READY   REASON
patient   http://patient-broker-ingress.mod-patient.svc.cluster.local   15m   8 OK / 8     True    
```

The cloud event client did not return an error when submitting the event.

 **Expected behavior**
Expected behavior is that the event processes through the broker and into the trigger.

 **To Reproduce**
Requirements: CertManager, RabbitMQ Operator and RabbitMQ Topology Operator

1) create ca with cert manager
2) create self signed issuer with ca from step 1
3) create tls certs with self signed issuer from step 2
4) create rabbitmq cluster using tls secret
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq
  namespace: rabbitmq
spec:
  replicas: 1
  tls:
    secretName: tls-secret
```
5) create rabbitmq broker config for knative
```
apiVersion: eventing.knative.dev/v1alpha1
kind: RabbitmqBrokerConfig
metadata:
  name: rmq-broker-config
  namespace: rabbitmq
spec:
  rabbitmqClusterReference:
    # Configure name if a RabbitMQ Cluster Operator is being used.
    name: rmq
    namespace: rabbitmq
    
  queueType: quorum
```
6) create broker
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
  name: test
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: rmq-broker-config
    namespace: rabbitmq
```
7) push event and check ingress logs

 **Knative release version**
1.8.5

 **Additional context**
I would be happy to investigate this as I need this for work. My guess is that there needs to be a way to provide a CA secret to the controller and/or ingress controller. The CA secret would have to exist in the namespace that the ingress controller is being created in.
