### ISSUE TITLE
Updating a trigger's deadLetterSink puts the queue into a bad state

### ISSUE THREAD

**Issue by benmoss** [knative-sandbox/eventing-rabbitmq#448]
There's not a way to update the dead letter exchange of a queue, so I think if we encounter the following scenario, the only option other than immutability would be to delete and recreate the queue.

- Declare a broker with a dead letter sink
- Declare a trigger with a dead letter sink
- Remove the DLS from the trigger

You'll see that the queue doesn't change to point to the broker's DLX, and if you inspect the queue CRD you'll see something like:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-10-04T15:59:05Z"
    message: 'Error 400 (bad_request): inequivalent arg ''x-dead-letter-exchange''
      for queue ''t.default.default.a8b1707f-b6aa-42e4-8707-664137715fcc'' in vhost
      ''/'': received ''b.default.default.dlx.51802894-5fff-43a6-949b-15b500b0c60e''
      but current is ''t.default.default.dlx.a8b1707f-b6aa-42e4-8707-664137715fcc'''
    reason: FailedCreateOrUpdate
    status: "False"
    type: Ready
```
### Blocker
- [ ] https://github.com/knative-sandbox/eventing-rabbitmq/issues/264
