### ISSUE TITLE
All eventing-rabbitmq pods use a restricted pod security standard profile

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#496]
**Problem**
Use a more restricted [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/).

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
This feature would be used by the K8s Cluster Administrator

**Exit Criteria**
All eventing-rabbitmq pods are run with a restricted pod security standard profile
```
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  capabilities:
    drop:
    - all
```

**Additional context (optional)**
[Reference Eventing PR](https://github.com/knative/eventing/pull/5863)
