### ISSUE TITLE
Deleting a RabbitMQ Source should delete the queue

### ISSUE THREAD

**Issue by gvmw** [knative-sandbox/eventing-rabbitmq#528]
**Describe the bug**
When a `RabbitmqSource` is deleted, the queue that it creates is left behind.
This was observed part of https://github.com/knative-sandbox/eventing-rabbitmq/pull/522#issuecomment-981820162

 **Expected behavior**
When the `RabbitmqSource` is deleted, the queue should be deleted too, otherwise it will continue receiving messages:
![image](https://user-images.githubusercontent.com/90614196/143911986-8360df30-4562-4214-8721-9c697b19ad0d.png)

 **To Reproduce**
Deploy the sample added in https://github.com/knative-sandbox/eventing-rabbitmq/pull/522. Delete the `RabbitmqSource` with the following config and observe the queue remaining behind.

```yaml
---
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: concurrent-dispatch
spec:
  brokers: "rabbitmq:5672/"
  topic: ""
  user:
    secretKeyRef:
      name: rabbitmq-default-user
      key: username
  password:
    secretKeyRef:
      name: rabbitmq-default-user
      key: password
  channel_config:
    prefetch_count: 10
    global_qos: false
  exchange_config:
    name: "eventing-rabbitmq-source"
    type: "fanout"
    durable: false
    auto_deleted: false
    internal: false
    nowait: false
  queue_config:
    name: "eventing-rabbitmq-source"
    routing_key: ""
    durable: false
    # TODO: should the queue be deleted when the source gets deleted?
    delete_when_unused: true
    exclusive: false
    nowait: false
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: concurrent-dispatch
```

 **Knative release version**
Tested with v1.0.0, eventing-rabbitmq dev version (#522) all running on GKE v1.21.5.

 **Additional context**
@gabo1208 shares the context.

It was observed that using the `Exclusive` flag results in the correct behaviour, so my suspicion is that this is a RabbitMQ issue.
