### ISSUE TITLE
no matches for kind "Broker" in version "eventing.knative.dev/v1 error

### ISSUE THREAD

**Issue by Gsantomaggio** [knative-sandbox/eventing-rabbitmq#77]
I am following the instructions here:
https://github.com/knative-sandbox/eventing-rabbitmq/tree/master/broker

Everything ok until I try:
```
kubectl apply -f - << EOF
  apiVersion: eventing.knative.dev/v1
  kind: Broker
  metadata:
    name: default
    annotations:
      eventing.knative.dev/broker.class: RabbitMQBroker
  spec:
    config:
      apiVersion: v1
      kind: Secret
      name: rokn-rabbitmq-broker-secret
EOF
```

I get this error:
```
no matches for kind "Broker" in version "eventing.knative.dev/v1"
```

Am I missing something? 

Thank you
