### ISSUE TITLE
Rabbitmq Dispatcher Closing Channel Randomly and Not Reconnecting

### ISSUE THREAD

**Issue by nkreiger** [knative-sandbox/eventing-rabbitmq#832]
```
Sending an event...
Sending an event....
{"level":"warn","ts":"...","logger":"rabbitmq-dispatcher","caller":"dispatcher/dispatcher.go:105","msg":"message channel closed, stopping message consumers"}
```

At random the dispatcher drops the connection and just sits there until I manually restart the pod and then it starts working again...it can last for 24 hours, 30 hours, or 2 hours, before it drops.

It ALWAYS drops 30 minutes after the last sent event, I'm just not sure what is causing it to drop

 **Expected behavior**
The dispatcher continues to listen on the queue.

 **To Reproduce**
Steps to reproduce the behavior.

https://knative.dev/docs/eventing/broker/rabbitmq-broker/

followed these steps.

created a broker
```yaml
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: knative-eventing-broker
    namespace: rabbitmq
  delivery:
    backoffDelay: PT0.25
    backoffPolicy: exponential
    retry: 10
```
created triggers from that broker

 **Knative release version**
1.4.0

 **Additional context**
huge blocker, thanks for the help :)...tried to track the code but it looks like it logs it out here:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/main/pkg/dispatcher/dispatcher.go#L114

but I'm not sure why it's not trying to reconnect here:

https://github.com/knative-sandbox/eventing-rabbitmq/blob/e527b3a4d780af8fcb55eb53bf8af5dedb78acfd/cmd/dispatcher/main.go#L113
