### ISSUE TITLE
Document configuring RMQ as the default broker on https://knative.dev/docs/eventing/configuration/broker-configuration/

### ISSUE THREAD

**Issue by xtreme-sameer-vohra** [knative-sandbox/eventing-rabbitmq#895]
**Problem**
User's don't know how to configure RMQ as default broker

**[Persona:](https://github.com/knative/eventing/blob/main/docs/personas.md)**
Which persona is this feature for?
System Operator

**Exit Criteria**
Documentation that a operator can follow to configure RMQ as default broker on a cluster

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve?

**Comment by xtreme-sameer-vohra** [comment]
Snippet with defaulting to RMQ Broker for `foo` namespace prior to 1.6
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  default-br-config: |
    namespaceDefaults:
      foo:
        brokerClass: RabbitMQBroker
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rabbitmq
        namespace: ns-with-rmq-cluster
kind: ConfigMap
metadata:   
  name: config-br-defaults
  namespace: knative-eventing
```
